"""Add Owner

Revision ID: 2d8f2be349e5
Revises: a018a0a153ed
Create Date: 2021-12-31 22:23:07.162442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d8f2be349e5'
down_revision = 'a018a0a153ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting', sa.Column('owner', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'meeting', 'user', ['owner'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meeting', type_='foreignkey')
    op.drop_column('meeting', 'owner')
    # ### end Alembic commands ###
