"""User table update

Revision ID: 846447a03544
Revises: 9e92685f41ea
Create Date: 2022-01-12 23:35:02.766176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '846447a03544'
down_revision = '9e92685f41ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('permission', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'permission')
    # ### end Alembic commands ###
