"""StaffCapability added

Revision ID: b93062c461a2
Revises: 6e62a216a750
Create Date: 2021-12-27 21:08:58.133046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b93062c461a2'
down_revision = '6e62a216a750'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_capability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff', sa.Integer(), nullable=False),
    sa.Column('skill', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['skill'], ['skill_set.id'], ),
    sa.ForeignKeyConstraint(['staff'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staff_capability')
    # ### end Alembic commands ###
