"""StaffCapability Foreign Key edited

Revision ID: 1c96be92bad0
Revises: b93062c461a2
Create Date: 2021-12-27 21:46:17.965359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c96be92bad0'
down_revision = 'b93062c461a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('staff_capability_ibfk_1', 'staff_capability', type_='foreignkey')
    op.drop_constraint('staff_capability_ibfk_2', 'staff_capability', type_='foreignkey')
    op.create_foreign_key(None, 'staff_capability', 'skill_set', ['skill'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'staff_capability', 'user', ['staff'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'staff_capability', type_='foreignkey')
    op.drop_constraint(None, 'staff_capability', type_='foreignkey')
    op.create_foreign_key('staff_capability_ibfk_2', 'staff_capability', 'user', ['staff'], ['id'])
    op.create_foreign_key('staff_capability_ibfk_1', 'staff_capability', 'skill_set', ['skill'], ['id'])
    # ### end Alembic commands ###
