"""Rename usertype to user_type to fit naming Convention, removing Mobile Phone

Revision ID: 6e62a216a750
Revises: 2b94302a0b1d
Create Date: 2021-12-27 20:02:40.823439

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6e62a216a750'
down_revision = '2b94302a0b1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_type', sa.Integer(), nullable=False))
    op.drop_column('user', 'mobile_phone')
    op.drop_column('user', 'usertype')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('usertype', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('mobile_phone', mysql.VARCHAR(length=11), nullable=True))
    op.drop_column('user', 'user_type')
    # ### end Alembic commands ###
